<?php
    // Get data saved in cart
    $cart = Mage::getModel('checkout/cart')->getQuote();
    $polcodeShippingId =  $cart->getShippingAddress()->getPolcodeShippingId();
    $polcodeDeliveryDate =  $cart->getShippingAddress()->getPolcodeDeliveryDate();
    
    echo $polcodeShippingId;
    echo $polcodeDeliveryDate;
    
?>

<!--Loader-->
<span id="delivery-calendar-please-wait" class="please-wait" style="display:none;">
    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" 
         alt="<?php echo Mage::helper('polcodeshipping')->quoteEscape($this->__('Recalculate Shipping ...')) ?>" title="<?php echo Mage::helper('polcodeshipping')->quoteEscape($this->__('Recalculate Shipping ...')) ?>" class="v-middle" /> <?php echo $this->__('Recalculate Shipping ...') ?>
</span>


<!--Display calendar-->
<div class="delivery_calendar">
    <input type="hidden" name="polcode_delivery_date" value="<?php echo $polcodeDeliveryDate ?>"/>
    <?php foreach ( $this->getCalendar()->getDays() as $day ) { ?>
    <div class="delivery_calendar_day">
        
        <p class="day_number"><?php echo  $day->getDayOfMonth() ?></p>
        <p class="month_name"><?php echo $day->getMonthRepresentation() ?></p>
        <p class="weekday_name"><?php echo $day->getWeekdayName() ?></p>
        <hr class="line"/>
        <?php foreach ( $day->getIntervals() as $interval ) { ?>
            <p class="hours"><?php echo $interval['hour_start'] ?> - <?php echo $interval['hour_end'] ?></p>
            <input <?php if ( $polcodeShippingId == $interval['id'] ) { ?> checked="checked" <?php } ?> type="radio" name="polcode_shipping_id" value="<?php echo $interval['id']?>"/>    
            <p class="price"><?php echo Mage::helper('core')->currency($interval['cost'], true, false); ?></p>
        <?php } ?>
        
    </div>
    <?php } ?>
    <div class="clear"></div>
</div>



<!--Reloads shipping method step-->
<script type="text/javascript">
//<![CDATA[
    var radioSelectorString = 'input[type="radio"][name="polcode_shipping_id"]';
    var radioSelectorString2 = 'input[type="radio"][name="shipping_method"]';
    var deliveryCalendarLoader = 'delivery-calendar-please-wait';

    // calendar radios
    $$(radioSelectorString).each(function(el){
        var url = '<?php echo $this->getChangeShippingDateUrl() ?>';
        dispatch(el, url);
    });
    
    // shipping method radios
    $$(radioSelectorString2).each(function(el){
        var url = '<?php echo $this->getChangeShippingMethodUrl() ?>';
        dispatch(el, url);
    });
    
    // refresh
    function dispatch( el, url ) {
        Event.observe(el, 'click', function(){
            if (el.checked == true){

                var value = el.getValue();

                $$(radioSelectorString).each( function(el){ el.disable(); } );
                $$(radioSelectorString2).each( function(el){ el.disable(); } );
                Element.show(deliveryCalendarLoader);

                new Ajax.Request(url, {
                    method: 'post',
                    parameters: { 'params': value },
                    onSuccess: function(transport){ 

                        //var json = transport.responseText.evalJSON();
                        shipping.nextStep(transport);  
                        $$(radioSelectorString).each( function(el){ el.enable(); } );
                        $$(radioSelectorString2).each( function(el){ el.enable(); } );
                        Element.hide(deliveryCalendarLoader);        

                    },
                    onFailure: function(){ 
                        $$(radioSelectorString).each( function(el){ el.enable(); } );
                    }
                }); 

            }
        });
    }
    
//]]>
</script>